### ISSUE TITLE
Subexpressions in helpers no longer work in ember 2.0.0-beta.1

### ISSUE THREAD

**Issue by Eptis** [stefanpenner/ember-moment#52]
this used to work:
```
{{moment date.date (t "app.defaultMomentFormat")}}
```
But now throws an error:
```
TypeError: format.match is not a function
```

**Comment by jasonmit** [comment]
Will investigate this today

**Comment by jasonmit** [comment]
I'm not able to reproduce this on the latest beta (beta4).  I've fixed other various issues with 2.0 in https://github.com/stefanpenner/ember-moment/pull/78

Be sure you're `t` helper is returning a format string as expected.
